name: Lab 4 GitHub Action

on: 
  push:
    branches: [ "master", "main" ]

jobs:
  lab-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Community action requirement

      - name: Execute Shell Command
        run: echo "GitHub Actions successfully executed for Bojan!" # Shell command requirement